### ISSUE TITLE
Patch for Gastronomy Null Method Error

### ISSUE THREAD

**Issue by Shrakna** [rwmt/Multiplayer-Compatibility#103]
> Exception: System.NullReferenceException: Null method for rimworld.multiplayer.compat

I figure you guys already know as it happened to so many different ones.

However also wanted to flag that after Sokyran patched Gastronomy Orion split the Cash Register off into a stand alone mod., which is required to play Gastronomy.
https://steamcommunity.com/sharedfiles/filedetails/?id=2506046833
Not sure if that means the original Compat patch also needs to be split apart as well to apply to both.

**Comment by SokyranTheDragon** [comment]
Could take a while to update. The patch was a little bit complex (which means it'd take time), and preferably I'd like to make it less hacky by making it possible to handle some cases from that mod using MP API (so it'd require changes to MP mod itself).
