### ISSUE TITLE
compile and post the release somewhere, please

### ISSUE THREAD

**Issue by IvanKonov** [rwmt/Multiplayer-Compatibility#273]
compile and post the release somewhere, please. My Game is not from Steam, but I would like to use the mod.

**Comment by notfood** [comment]
If you can edit this one to compile it and put it on pre-release on push, I'll appreciate it.

https://github.com/rwmt/Multiplayer-Compatibility/pull/252

**Comment by Bonaducci** [comment]
It's not much but it may help anyone looking for it.
This is May 17 2023 build.
[Multiplayer-Compatibility.zip](https://github.com/rwmt/Multiplayer-Compatibility/files/11643092/Multiplayer-Compatibility.zip)

**Comment by quindao** [comment]
if anyone stumbles apon this and is look for up to date versions they can use the steam downloader function of the rimpy mod manager to download the steam versions of mods without having the steam version of the game

**Comment by Zetrith** [comment]
New versions are now automatically published as GitHub releases

https://github.com/rwmt/Multiplayer-Compatibility/releases
