### ISSUE TITLE
Vanilla Psycasts Expanded - Error on startup

### ISSUE THREAD

**Issue by Feliphysics** [rwmt/Multiplayer-Compatibility#292]
Don't know if it's a relevant error, seems to be related to the gyzmo of a specific psycast (skip-door).

[Player.log](https://github.com/rwmt/Multiplayer-Compatibility/files/11071577/Player.log)

**Comment by notfood** [comment]
Fixed by https://github.com/rwmt/Multiplayer-Compatibility/pull/293
