### ISSUE TITLE
[AllowTool] Desync when using "Strip Mine" and "Mine Connected Ores"

### ISSUE THREAD

**Issue by Mihokyo** [rwmt/Multiplayer-Compatibility#34]
**Version Data**
Multiplayer Mod Version|**0.5.1.7**
Rimworld Version and Rev|**1.1.2654 rev672**

We was 3 on the games, and we already all redownload the mod and check game integrity.

Without arbiter i don't desync has host but all player desync
If arbiter enable, i desync like all player

This is a desync file from me (the host), if you want a desync from a player give me a sign, and i will send it
[Desync-155.zip](https://github.com/rwmt/Multiplayer-Compatibility/files/5007549/Desync-155.zip)

**Comment by notfood** [comment]
Multiplayer-Compatibility doesn't support AllowTool.

Currently, there is a native Multiplayer Allow Tool Beta version in the Multiplayer Discord. Report over there, this doesn't belong here.
