### ISSUE TITLE
Time Of Day Switches mod packageId mismatch with MPCompat patch target id string.

### ISSUE THREAD

**Issue by ubergarm** [rwmt/Multiplayer-Compatibility#434]
While working out the desyncs in my current multiplayer modpack, I was checking the startup logs to confirm that mods that requiring MPCompat mod were actually being patched. (As with all the forks, abandoned mods, and reloaded versions sometimes the package id can change etc).

I noticed that while I have [Time-of-Day Switches](https://steamcommunity.com/sharedfiles/filedetails/?id=776114412) in my mod list, the startup logs suggested it is *not* getting patched e.g. here is an example of the line for `Alpha Animals` where it *does* find and patch:

```
MPCompat :: Initialized compatibility for sarg.alphaanimals
.
.
.
# no mention ever of patching Time Of Day Switches Mod
```

The Multiplayer-Compatibility [mod code](https://github.com/rwmt/Multiplayer-Compatibility/blob/master/Source/Mods/TimeOfDAySwitch.cs#L10
)  seems to be targeting the mod id string name `Merthsoft.TimeOfDaySwitches`...

However, if you look at the `About.xml` for that specific mod (the steam id number matches the README.md URLs link as well as the code comment) it has a `packageId` without the `s`:

```bash
$ cat 776114412/About/About.xml | grep packageId
  <packageId>Merthsoft.TimeOfDaySwitch</packageId>
```

Following the comment in this MPCompat code to the bitbucket code [bitbucket code repo](https://bitbucket.org/merthsoft/timeofdayswitch/src/7a766b82520df52be85d78564ef8363f7da614f9/About/About.xml#lines-10) for what looks like an older version of the mod, it seems the mod itself changed names at some point along the way.

You can see on the [github link listed on the mod page](https://github.com/merthsoft/time-of-day-switch/blob/master/About/About.xml#L14) that the name indeed has since dropped the `s`. However I don't see exactly where that happened in the [git blame](https://github.com/merthsoft/time-of-day-switch/commit/09b83d535730ee9bbc12482434760b8e4623f8ff)...

I am guessing this mismatch is why it seems to *not* actually be triggering the patch from what I can tell. I did not make it far enough to my game to actually test it however to see if it still needs to be patched or if setting the value causes a desync.

Cheers!

**Comment by notfood** [comment]
Thanks! Very helpful explanation. I updated it to what the github repo says.

**Comment by ubergarm** [comment]
Wow thanks, so fast!

I appreciate all the work you put into this community, and am impressed by your Multiplayer-able mod pack as well as numerous mods! Thanks so much!
