### ISSUE TITLE
Desync when using any of the vanilla psycast expanded abilities

### ISSUE THREAD

**Issue by Lina28011** [rwmt/Multiplayer-Compatibility#443]
in case of me or myu host using any of psyonic spells from VPE, desync occurs. We tested it on different saves it is not case of map or any other mod. Host and local traces shows that only one either host or user is experiencing the casting of spell, when in other's game nothing happens and game desyncs. It was ok just other week, so i think it is latest update of compat that broke it.

**Comment by notfood** [comment]
Needs more triage before landing here, next time ask around Discord first.
