### ISSUE TITLE
Vanilla extended brewing can't added on cooking workbench 

### ISSUE THREAD

**Issue by REFIRSER2** [rwmt/Multiplayer-Compatibility#452]
I'm playing multiplayer with multifaction on 1.4 version.
I added vanilla extended brewing.
But i can't added it on cooking workbench.

**Comment by SokyranTheDragon** [comment]
Closing since:
- We no longer support 1.4, only 1.5
- There's no logs
- The message doesn't really explain what's broken, and I'm not going to start guessing what the issue may be
