### ISSUE TITLE
Rimworld of Magic - Cannot cast spells

### ISSUE THREAD

**Issue by Shanna3229** [rwmt/Multiplayer-Compatibility#473]
I was really excited to see the compatibility addition for a rimworld of magic, but when I'm hosting a multiplayer game, neither I nor my friend can cast spells in game. Even if they haven't tried to load in yet, it throws an error and the pawns won't cast. I'd love to be able to play with my friend if anyone has any advice on how to fix this.

**Comment by SokyranTheDragon** [comment]
Post your log file (the one in which the error occurs in). Can't help without it.
