### ISSUE TITLE
Vanilla Expanded Framework

### ISSUE THREAD

**Issue by theblu3j** [rwmt/Multiplayer-Compatibility#475]
Vanilla Expanded Framework seems to be causing issues with Multiplayer currently because of this:
![image](https://github.com/user-attachments/assets/1978f80f-1ab5-441d-80d9-65ffba06d05f)
Which is from what I can tell Vanilla Expanded Framework due to the only WorldGenStep XML I can find under both the Data folder and my mod folders is in the Vanilla Expanded Framework mod folder.

**Comment by SokyranTheDragon** [comment]
Any more info? Log files? A single screenshot is not nearly enough to help with an issue. And it works fine on my end.

**Comment by theblu3j** [comment]
Yeah that was my bad. Wrote this up at 4AM while half asleep. WorldGenStepDef was an XML under the Vanilla Expanded Framework folder so I figured that was it. Anyways, had more time to figure this out recently and after disabling half of my mods over and over to narrow down which it was it turns out it was ReGrowth. Unsure if it's just in combination with VEF or in general.
