### ISSUE TITLE
Switch to packageId for mod identification

### ISSUE THREAD

**Issue by notfood** [rwmt/Multiplayer-Compatibility#7]
Names are very inconsistant, we should be using packageId from now on. So we need to identify all the supported mods first.

**Comment by Nebual** [comment]
Also adding all targetted mods as "LoadAfter"'s would probably help, while you're already fetching the packageIds

**Comment by notfood** [comment]
Mod Order doesn't apply, we aren't messing with XML or Patches. ModCompatibility should always go after Multiplayer.
